#!/usr/bin/env bash
# a bash script to transfer a file from a client to a server.
#PATH_TO_FILE to be copied to server USER on server IP of server
#location to copy to on server and PATH_TO_IDENTITY_FILE for user

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	else
		scp -o StritHostkeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
